before:
  hooks:
    - go mod tidy
builds:
  - id: comby
    main: ./main.go
    binary: comby
    env:
      - CGO_ENABLED=0
    targets:
      - darwin_amd64
      - darwin_arm64
      - linux_386
      - linux_amd64
      - linux_arm
      - linux_arm64
      - windows_386
      - windows_amd64
    ldflags:
      - -s -w -X main.Version={{.Version}}
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Version }}-next"
release:
  github:
    owner: markliederbach
    name: comby